image: node:14.20
#options:
#  docker: true
#  size: 2x
pipelines:
  branches:
    develop:
      - step:
          name: Installation
#          caches:
#            - node
          size: 2x
          script:
            - export NODE_OPTIONS=--max_old_space_size=6144
            - npm install
          artifacts:
            - node_modules/** # Save modules for next steps
      - step:
            name: Build
            caches:
              - node
            size: 2x  
            script:
              - export NODE_OPTIONS=--max_old_space_size=6144            
              - npm run build-test
            artifacts:
              - dist/** # Save modules for next steps
      - step:
            name: S3 Deploy
            script:
              - pipe: atlassian/aws-s3-deploy:0.3.8
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: 'us-east-2'
                  S3_BUCKET: 'test2.automationhq.ai'
                  LOCAL_PATH: 'dist'
                  ACL: 'public-read'
      - step:
            name: cloudfront Invalidation
            script:
              - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  DISTRIBUTION_ID: 'E1G4Z3OLAHCPRY'
                  PATHS: '/*'